version: "3.7"

services:
  mongo:
    image: mongo
    container_name: s-api-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      # - MONGO_INITDB_DATABASE=laxzdb
    volumes:
      - ${DB_PATH}:/data/db
    ports:
      - "27017:27017" # to access from mongo compass
    networks:
      - api-network
  api-app:
    # build: .
    image: node:alpine
    container_name: s-api-app
    command: ["yarn", "${RUNNING_MODE}"]
    ports:
      - "3003:3001"
    environment: 
      UID: "${UID:-0}"
    working_dir: /app
    volumes: 
      - .:/app:delegated
    depends_on:
      - mongo
    networks:
      - api-network

networks:
  api-network:
    external: true
